// <auto-generated />
using System;
using BadmintonApp.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace BadmintonApp.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20251111174126_IsSystemAdded2")]
    partial class IsSystemAdded2
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("BadmintonApp.Domain.Clubs.Club", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Address")
                        .HasColumnType("text");

                    b.Property<string>("City")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.Property<int>("TotalCourts")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.ToTable("Clubs");
                });

            modelBuilder.Entity("BadmintonApp.Domain.Core.Permission", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("Type")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.ToTable("Permissions");

                    b.HasData(
                        new
                        {
                            Id = new Guid("bb144aa6-d452-4c65-8dd8-26e83a343d10"),
                            Type = 1
                        },
                        new
                        {
                            Id = new Guid("dc24d312-1e12-455e-b58d-6a5e0e1c5a26"),
                            Type = 2
                        },
                        new
                        {
                            Id = new Guid("c17101a7-c7f5-4cfc-99c4-c9e7bff062e0"),
                            Type = 3
                        },
                        new
                        {
                            Id = new Guid("e804d9ec-17e5-4cb1-97fd-d033379b2a1e"),
                            Type = 4
                        },
                        new
                        {
                            Id = new Guid("f42d1226-3c8a-4690-a9cb-702d81e9d134"),
                            Type = 5
                        },
                        new
                        {
                            Id = new Guid("6e378e33-7c14-41d8-9005-3211ac337ada"),
                            Type = 20
                        },
                        new
                        {
                            Id = new Guid("fbcc2933-164c-4f37-a9e7-11868c34dc64"),
                            Type = 21
                        },
                        new
                        {
                            Id = new Guid("bcfd34b3-d0aa-4a84-a68e-d1c58e0a0f36"),
                            Type = 22
                        },
                        new
                        {
                            Id = new Guid("e30aa5ae-2e19-4a5b-a9be-40cc74bb25e4"),
                            Type = 23
                        },
                        new
                        {
                            Id = new Guid("4fd7483a-2436-4c2c-bdd3-275e595dcd1e"),
                            Type = 24
                        },
                        new
                        {
                            Id = new Guid("2264ae2c-73b2-4a8f-8e92-cc38d4cd6b6c"),
                            Type = 25
                        },
                        new
                        {
                            Id = new Guid("b3a08f9f-263e-42cc-b02a-85b5c6a5979b"),
                            Type = 26
                        },
                        new
                        {
                            Id = new Guid("66d2b5fd-f0fd-4c29-92d6-e165fce4096f"),
                            Type = 50
                        },
                        new
                        {
                            Id = new Guid("e47c2949-6cf3-4c2f-b6b0-e252b456cacf"),
                            Type = 51
                        },
                        new
                        {
                            Id = new Guid("94a13b97-2e03-41df-9c4e-84db8f5a05a1"),
                            Type = 52
                        },
                        new
                        {
                            Id = new Guid("7c918f93-79b3-4f0f-91de-798a888d8ec9"),
                            Type = 80
                        },
                        new
                        {
                            Id = new Guid("f88b5e0f-78ec-40b0-ade6-dc6c0414d6b4"),
                            Type = 81
                        },
                        new
                        {
                            Id = new Guid("6c2dba59-81c2-4d06-a476-66c7cf930a50"),
                            Type = 90
                        },
                        new
                        {
                            Id = new Guid("9f29376d-dbc5-4a1a-85c3-cd6d0cbac9a6"),
                            Type = 91
                        },
                        new
                        {
                            Id = new Guid("95a05b7b-e88d-48c1-9e65-0cfc2c4a09f6"),
                            Type = 92
                        },
                        new
                        {
                            Id = new Guid("79d4ef1a-8a4a-4cb2-b63a-2307698de15b"),
                            Type = 110
                        },
                        new
                        {
                            Id = new Guid("274e546f-78b0-4dc2-a7bc-548f5e92f4cc"),
                            Type = 111
                        },
                        new
                        {
                            Id = new Guid("4a6970f1-ff3e-43fd-9172-c4f3f6c2c4c7"),
                            Type = 130
                        },
                        new
                        {
                            Id = new Guid("f3a9df19-ea7c-4a90-a3ee-238c7f745f5f"),
                            Type = 140
                        },
                        new
                        {
                            Id = new Guid("aa0d8c57-e388-4db4-9746-b6cc4b47fd0d"),
                            Type = 160
                        },
                        new
                        {
                            Id = new Guid("1740be12-b8a1-40db-b184-d43fd3f6b0fa"),
                            Type = 180
                        },
                        new
                        {
                            Id = new Guid("d474449e-3045-4418-89c7-5a7599e58033"),
                            Type = 181
                        });
                });

            modelBuilder.Entity("BadmintonApp.Domain.Core.Player", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("Level")
                        .HasColumnType("integer");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("Players");
                });

            modelBuilder.Entity("BadmintonApp.Domain.Core.Role", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<bool>("IsSystem")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Roles");

                    b.HasData(
                        new
                        {
                            Id = new Guid("98e5cfcd-cada-486a-96bb-30b6a9a60174"),
                            IsSystem = true,
                            Name = "ClubAdmin"
                        },
                        new
                        {
                            Id = new Guid("bb074c39-08df-45d9-8e74-5b6a07257883"),
                            IsSystem = true,
                            Name = "ClubManager"
                        },
                        new
                        {
                            Id = new Guid("5b0ac8d3-e270-422f-af95-99e8be79e47a"),
                            IsSystem = true,
                            Name = "ClubTrainer"
                        });
                });

            modelBuilder.Entity("BadmintonApp.Domain.Core.RolePermission", b =>
                {
                    b.Property<Guid>("RoleId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("PermissionId")
                        .HasColumnType("uuid");

                    b.HasKey("RoleId", "PermissionId");

                    b.HasIndex("PermissionId");

                    b.ToTable("RolePermissions");

                    b.HasData(
                        new
                        {
                            RoleId = new Guid("98e5cfcd-cada-486a-96bb-30b6a9a60174"),
                            PermissionId = new Guid("bb144aa6-d452-4c65-8dd8-26e83a343d10")
                        },
                        new
                        {
                            RoleId = new Guid("98e5cfcd-cada-486a-96bb-30b6a9a60174"),
                            PermissionId = new Guid("dc24d312-1e12-455e-b58d-6a5e0e1c5a26")
                        },
                        new
                        {
                            RoleId = new Guid("98e5cfcd-cada-486a-96bb-30b6a9a60174"),
                            PermissionId = new Guid("c17101a7-c7f5-4cfc-99c4-c9e7bff062e0")
                        },
                        new
                        {
                            RoleId = new Guid("98e5cfcd-cada-486a-96bb-30b6a9a60174"),
                            PermissionId = new Guid("e804d9ec-17e5-4cb1-97fd-d033379b2a1e")
                        },
                        new
                        {
                            RoleId = new Guid("98e5cfcd-cada-486a-96bb-30b6a9a60174"),
                            PermissionId = new Guid("f42d1226-3c8a-4690-a9cb-702d81e9d134")
                        },
                        new
                        {
                            RoleId = new Guid("98e5cfcd-cada-486a-96bb-30b6a9a60174"),
                            PermissionId = new Guid("6e378e33-7c14-41d8-9005-3211ac337ada")
                        },
                        new
                        {
                            RoleId = new Guid("98e5cfcd-cada-486a-96bb-30b6a9a60174"),
                            PermissionId = new Guid("fbcc2933-164c-4f37-a9e7-11868c34dc64")
                        },
                        new
                        {
                            RoleId = new Guid("98e5cfcd-cada-486a-96bb-30b6a9a60174"),
                            PermissionId = new Guid("bcfd34b3-d0aa-4a84-a68e-d1c58e0a0f36")
                        },
                        new
                        {
                            RoleId = new Guid("98e5cfcd-cada-486a-96bb-30b6a9a60174"),
                            PermissionId = new Guid("e30aa5ae-2e19-4a5b-a9be-40cc74bb25e4")
                        },
                        new
                        {
                            RoleId = new Guid("98e5cfcd-cada-486a-96bb-30b6a9a60174"),
                            PermissionId = new Guid("4fd7483a-2436-4c2c-bdd3-275e595dcd1e")
                        },
                        new
                        {
                            RoleId = new Guid("98e5cfcd-cada-486a-96bb-30b6a9a60174"),
                            PermissionId = new Guid("2264ae2c-73b2-4a8f-8e92-cc38d4cd6b6c")
                        },
                        new
                        {
                            RoleId = new Guid("98e5cfcd-cada-486a-96bb-30b6a9a60174"),
                            PermissionId = new Guid("b3a08f9f-263e-42cc-b02a-85b5c6a5979b")
                        },
                        new
                        {
                            RoleId = new Guid("98e5cfcd-cada-486a-96bb-30b6a9a60174"),
                            PermissionId = new Guid("66d2b5fd-f0fd-4c29-92d6-e165fce4096f")
                        },
                        new
                        {
                            RoleId = new Guid("98e5cfcd-cada-486a-96bb-30b6a9a60174"),
                            PermissionId = new Guid("e47c2949-6cf3-4c2f-b6b0-e252b456cacf")
                        },
                        new
                        {
                            RoleId = new Guid("98e5cfcd-cada-486a-96bb-30b6a9a60174"),
                            PermissionId = new Guid("94a13b97-2e03-41df-9c4e-84db8f5a05a1")
                        },
                        new
                        {
                            RoleId = new Guid("98e5cfcd-cada-486a-96bb-30b6a9a60174"),
                            PermissionId = new Guid("7c918f93-79b3-4f0f-91de-798a888d8ec9")
                        },
                        new
                        {
                            RoleId = new Guid("98e5cfcd-cada-486a-96bb-30b6a9a60174"),
                            PermissionId = new Guid("f88b5e0f-78ec-40b0-ade6-dc6c0414d6b4")
                        },
                        new
                        {
                            RoleId = new Guid("98e5cfcd-cada-486a-96bb-30b6a9a60174"),
                            PermissionId = new Guid("6c2dba59-81c2-4d06-a476-66c7cf930a50")
                        },
                        new
                        {
                            RoleId = new Guid("98e5cfcd-cada-486a-96bb-30b6a9a60174"),
                            PermissionId = new Guid("9f29376d-dbc5-4a1a-85c3-cd6d0cbac9a6")
                        },
                        new
                        {
                            RoleId = new Guid("98e5cfcd-cada-486a-96bb-30b6a9a60174"),
                            PermissionId = new Guid("95a05b7b-e88d-48c1-9e65-0cfc2c4a09f6")
                        },
                        new
                        {
                            RoleId = new Guid("98e5cfcd-cada-486a-96bb-30b6a9a60174"),
                            PermissionId = new Guid("79d4ef1a-8a4a-4cb2-b63a-2307698de15b")
                        },
                        new
                        {
                            RoleId = new Guid("98e5cfcd-cada-486a-96bb-30b6a9a60174"),
                            PermissionId = new Guid("274e546f-78b0-4dc2-a7bc-548f5e92f4cc")
                        },
                        new
                        {
                            RoleId = new Guid("98e5cfcd-cada-486a-96bb-30b6a9a60174"),
                            PermissionId = new Guid("4a6970f1-ff3e-43fd-9172-c4f3f6c2c4c7")
                        },
                        new
                        {
                            RoleId = new Guid("98e5cfcd-cada-486a-96bb-30b6a9a60174"),
                            PermissionId = new Guid("f3a9df19-ea7c-4a90-a3ee-238c7f745f5f")
                        },
                        new
                        {
                            RoleId = new Guid("98e5cfcd-cada-486a-96bb-30b6a9a60174"),
                            PermissionId = new Guid("aa0d8c57-e388-4db4-9746-b6cc4b47fd0d")
                        },
                        new
                        {
                            RoleId = new Guid("98e5cfcd-cada-486a-96bb-30b6a9a60174"),
                            PermissionId = new Guid("1740be12-b8a1-40db-b184-d43fd3f6b0fa")
                        },
                        new
                        {
                            RoleId = new Guid("98e5cfcd-cada-486a-96bb-30b6a9a60174"),
                            PermissionId = new Guid("d474449e-3045-4418-89c7-5a7599e58033")
                        },
                        new
                        {
                            RoleId = new Guid("5b0ac8d3-e270-422f-af95-99e8be79e47a"),
                            PermissionId = new Guid("6e378e33-7c14-41d8-9005-3211ac337ada")
                        },
                        new
                        {
                            RoleId = new Guid("5b0ac8d3-e270-422f-af95-99e8be79e47a"),
                            PermissionId = new Guid("fbcc2933-164c-4f37-a9e7-11868c34dc64")
                        },
                        new
                        {
                            RoleId = new Guid("5b0ac8d3-e270-422f-af95-99e8be79e47a"),
                            PermissionId = new Guid("bcfd34b3-d0aa-4a84-a68e-d1c58e0a0f36")
                        },
                        new
                        {
                            RoleId = new Guid("5b0ac8d3-e270-422f-af95-99e8be79e47a"),
                            PermissionId = new Guid("e30aa5ae-2e19-4a5b-a9be-40cc74bb25e4")
                        },
                        new
                        {
                            RoleId = new Guid("5b0ac8d3-e270-422f-af95-99e8be79e47a"),
                            PermissionId = new Guid("4fd7483a-2436-4c2c-bdd3-275e595dcd1e")
                        },
                        new
                        {
                            RoleId = new Guid("5b0ac8d3-e270-422f-af95-99e8be79e47a"),
                            PermissionId = new Guid("2264ae2c-73b2-4a8f-8e92-cc38d4cd6b6c")
                        },
                        new
                        {
                            RoleId = new Guid("5b0ac8d3-e270-422f-af95-99e8be79e47a"),
                            PermissionId = new Guid("b3a08f9f-263e-42cc-b02a-85b5c6a5979b")
                        });
                });

            modelBuilder.Entity("BadmintonApp.Domain.Core.Staff", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("ClubId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamptz")
                        .HasDefaultValueSql("timezone('utc', now())");

                    b.Property<string>("Currency")
                        .HasColumnType("text");

                    b.Property<int>("EmploymentType")
                        .HasColumnType("integer");

                    b.Property<DateOnly?>("EndDate")
                        .HasColumnType("date");

                    b.Property<decimal>("HourlyRate")
                        .HasColumnType("numeric");

                    b.Property<decimal>("MonthlySalary")
                        .HasColumnType("numeric");

                    b.Property<string>("Notes")
                        .HasColumnType("text");

                    b.Property<string>("PayrollNotes")
                        .HasColumnType("text");

                    b.Property<decimal>("PerTrainingRate")
                        .HasColumnType("numeric");

                    b.Property<int>("PositionType")
                        .HasColumnType("integer");

                    b.Property<int>("SalaryType")
                        .HasColumnType("integer");

                    b.Property<int>("StaffStatus")
                        .HasColumnType("integer");

                    b.Property<DateOnly>("StartDate")
                        .HasColumnType("date");

                    b.Property<string>("StatusReason")
                        .HasColumnType("text");

                    b.Property<string>("TimeZone")
                        .HasColumnType("text");

                    b.Property<string>("Title")
                        .HasColumnType("text");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamptz");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("ClubId");

                    b.HasIndex("UserId");

                    b.ToTable("Staffs");
                });

            modelBuilder.Entity("BadmintonApp.Domain.Core.StaffClubRole", b =>
                {
                    b.Property<Guid>("StaffId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("RoleId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("ClubId")
                        .HasColumnType("uuid");

                    b.HasKey("StaffId", "RoleId", "ClubId");

                    b.HasIndex("ClubId");

                    b.HasIndex("RoleId");

                    b.ToTable("StaffClubRoles");
                });

            modelBuilder.Entity("BadmintonApp.Domain.Core.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid?>("ClubId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("DoB")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Email")
                        .HasColumnType("text");

                    b.Property<string>("FirstName")
                        .HasColumnType("text");

                    b.Property<string>("ImageUrl")
                        .HasColumnType("text");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsAdmin")
                        .HasColumnType("boolean");

                    b.Property<string>("LastName")
                        .HasColumnType("text");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("text");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("BadmintonApp.Domain.Logs.Log", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("ExceptionJson")
                        .HasColumnType("text");

                    b.Property<int>("Level")
                        .HasColumnType("integer");

                    b.Property<string>("Message")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Logs");
                });

            modelBuilder.Entity("BadmintonApp.Domain.Trainings.Training", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.PrimitiveCollection<int[]>("AllowedLevels")
                        .HasColumnType("integer[]");

                    b.Property<Guid>("ClubId")
                        .HasColumnType("uuid");

                    b.Property<int>("CourtsUsed")
                        .HasColumnType("integer");

                    b.Property<DateTime>("Date")
                        .HasColumnType("timestamp with time zone");

                    b.Property<TimeOnly>("EndTime")
                        .HasColumnType("time without time zone");

                    b.Property<bool>("IsRecurringWeekly")
                        .HasColumnType("boolean");

                    b.Property<Guid?>("LocationId")
                        .HasColumnType("uuid");

                    b.Property<int>("MaxPlayers")
                        .HasColumnType("integer");

                    b.Property<TimeOnly>("StartTime")
                        .HasColumnType("time without time zone");

                    b.Property<Guid?>("TrainerId")
                        .HasColumnType("uuid");

                    b.Property<int>("Type")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.ToTable("Trainings");
                });

            modelBuilder.Entity("BadmintonApp.Domain.Trainings.TrainingParticipant", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("RegisteredAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("TrainingId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("TrainingId");

                    b.ToTable("TrainingParticipants");
                });

            modelBuilder.Entity("BadmintonApp.Domain.Trainings.TrainingQueueEntry", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("QueuedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("TrainingId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("TrainingId");

                    b.ToTable("TrainingQueueEntries");
                });

            modelBuilder.Entity("BadmintonApp.Domain.WorkingHours.WorkingHour", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid?>("ClubId")
                        .HasColumnType("uuid");

                    b.Property<int>("DayOfWeek")
                        .HasColumnType("integer");

                    b.Property<TimeOnly?>("EndTime")
                        .HasColumnType("time without time zone");

                    b.Property<Guid?>("StaffId")
                        .HasColumnType("uuid");

                    b.Property<TimeOnly?>("StartTime")
                        .HasColumnType("time without time zone");

                    b.HasKey("Id");

                    b.HasIndex("ClubId");

                    b.HasIndex("StaffId");

                    b.ToTable("WorkingHours");
                });

            modelBuilder.Entity("BadmintonApp.Domain.Core.Player", b =>
                {
                    b.HasOne("BadmintonApp.Domain.Core.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("BadmintonApp.Domain.Core.RolePermission", b =>
                {
                    b.HasOne("BadmintonApp.Domain.Core.Permission", "Permission")
                        .WithMany("RolePermissions")
                        .HasForeignKey("PermissionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BadmintonApp.Domain.Core.Role", "Role")
                        .WithMany("RolePermissions")
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Permission");

                    b.Navigation("Role");
                });

            modelBuilder.Entity("BadmintonApp.Domain.Core.Staff", b =>
                {
                    b.HasOne("BadmintonApp.Domain.Clubs.Club", "Club")
                        .WithMany()
                        .HasForeignKey("ClubId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BadmintonApp.Domain.Core.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Club");

                    b.Navigation("User");
                });

            modelBuilder.Entity("BadmintonApp.Domain.Core.StaffClubRole", b =>
                {
                    b.HasOne("BadmintonApp.Domain.Clubs.Club", "Club")
                        .WithMany("UserRoles")
                        .HasForeignKey("ClubId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BadmintonApp.Domain.Core.Role", "Role")
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BadmintonApp.Domain.Core.Staff", "Staff")
                        .WithMany()
                        .HasForeignKey("StaffId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Club");

                    b.Navigation("Role");

                    b.Navigation("Staff");
                });

            modelBuilder.Entity("BadmintonApp.Domain.Trainings.TrainingParticipant", b =>
                {
                    b.HasOne("BadmintonApp.Domain.Trainings.Training", null)
                        .WithMany("Participants")
                        .HasForeignKey("TrainingId");
                });

            modelBuilder.Entity("BadmintonApp.Domain.Trainings.TrainingQueueEntry", b =>
                {
                    b.HasOne("BadmintonApp.Domain.Trainings.Training", null)
                        .WithMany("Queue")
                        .HasForeignKey("TrainingId");
                });

            modelBuilder.Entity("BadmintonApp.Domain.WorkingHours.WorkingHour", b =>
                {
                    b.HasOne("BadmintonApp.Domain.Clubs.Club", "Club")
                        .WithMany("WorkingHours")
                        .HasForeignKey("ClubId");

                    b.HasOne("BadmintonApp.Domain.Core.Staff", "Staff")
                        .WithMany("WorkingHours")
                        .HasForeignKey("StaffId");

                    b.Navigation("Club");

                    b.Navigation("Staff");
                });

            modelBuilder.Entity("BadmintonApp.Domain.Clubs.Club", b =>
                {
                    b.Navigation("UserRoles");

                    b.Navigation("WorkingHours");
                });

            modelBuilder.Entity("BadmintonApp.Domain.Core.Permission", b =>
                {
                    b.Navigation("RolePermissions");
                });

            modelBuilder.Entity("BadmintonApp.Domain.Core.Role", b =>
                {
                    b.Navigation("RolePermissions");
                });

            modelBuilder.Entity("BadmintonApp.Domain.Core.Staff", b =>
                {
                    b.Navigation("WorkingHours");
                });

            modelBuilder.Entity("BadmintonApp.Domain.Trainings.Training", b =>
                {
                    b.Navigation("Participants");

                    b.Navigation("Queue");
                });
#pragma warning restore 612, 618
        }
    }
}
