// <auto-generated />
using System;
using BadmintonApp.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace BadmintonApp.Infrastructure.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20251017091811_MakeStaffEndDateNullable")]
    partial class MakeStaffEndDateNullable
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.7");

            modelBuilder.Entity("BadmintonApp.Domain.Clubs.Club", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("Address")
                        .HasColumnType("TEXT");

                    b.Property<string>("City")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .HasColumnType("TEXT");

                    b.Property<int>("TotalCourts")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("Clubs");
                });

            modelBuilder.Entity("BadmintonApp.Domain.Core.Permission", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Permissions");

                    b.HasData(
                        new
                        {
                            Id = new Guid("bb144aa6-d452-4c65-8dd8-26e83a343d10"),
                            Name = "ClubView"
                        },
                        new
                        {
                            Id = new Guid("dc24d312-1e12-455e-b58d-6a5e0e1c5a26"),
                            Name = "ClubSettingsManage"
                        },
                        new
                        {
                            Id = new Guid("c17101a7-c7f5-4cfc-99c4-c9e7bff062e0"),
                            Name = "LocationsView"
                        },
                        new
                        {
                            Id = new Guid("e804d9ec-17e5-4cb1-97fd-d033379b2a1e"),
                            Name = "LocationsManage"
                        },
                        new
                        {
                            Id = new Guid("f42d1226-3c8a-4690-a9cb-702d81e9d134"),
                            Name = "CourtsManage"
                        },
                        new
                        {
                            Id = new Guid("6e378e33-7c14-41d8-9005-3211ac337ada"),
                            Name = "TrainingsView"
                        },
                        new
                        {
                            Id = new Guid("fbcc2933-164c-4f37-a9e7-11868c34dc64"),
                            Name = "TrainingsManage"
                        },
                        new
                        {
                            Id = new Guid("bcfd34b3-d0aa-4a84-a68e-d1c58e0a0f36"),
                            Name = "TrainingsRegisterPlayer"
                        },
                        new
                        {
                            Id = new Guid("e30aa5ae-2e19-4a5b-a9be-40cc74bb25e4"),
                            Name = "TrainingsCancelPlayer"
                        },
                        new
                        {
                            Id = new Guid("4fd7483a-2436-4c2c-bdd3-275e595dcd1e"),
                            Name = "TrainingsQueueManage"
                        },
                        new
                        {
                            Id = new Guid("2264ae2c-73b2-4a8f-8e92-cc38d4cd6b6c"),
                            Name = "TrainingsAttendanceMark"
                        },
                        new
                        {
                            Id = new Guid("b3a08f9f-263e-42cc-b02a-85b5c6a5979b"),
                            Name = "TrainingsLevelOverride"
                        },
                        new
                        {
                            Id = new Guid("66d2b5fd-f0fd-4c29-92d6-e165fce4096f"),
                            Name = "PlayersView"
                        },
                        new
                        {
                            Id = new Guid("e47c2949-6cf3-4c2f-b6b0-e252b456cacf"),
                            Name = "PlayersManage"
                        },
                        new
                        {
                            Id = new Guid("94a13b97-2e03-41df-9c4e-84db8f5a05a1"),
                            Name = "PlayersBalanceManage"
                        },
                        new
                        {
                            Id = new Guid("7c918f93-79b3-4f0f-91de-798a888d8ec9"),
                            Name = "StaffView"
                        },
                        new
                        {
                            Id = new Guid("f88b5e0f-78ec-40b0-ade6-dc6c0414d6b4"),
                            Name = "StaffManage"
                        },
                        new
                        {
                            Id = new Guid("6c2dba59-81c2-4d06-a476-66c7cf930a50"),
                            Name = "RolesView"
                        },
                        new
                        {
                            Id = new Guid("9f29376d-dbc5-4a1a-85c3-cd6d0cbac9a6"),
                            Name = "RolesManage"
                        },
                        new
                        {
                            Id = new Guid("95a05b7b-e88d-48c1-9e65-0cfc2c4a09f6"),
                            Name = "RolePermissionsAssign"
                        },
                        new
                        {
                            Id = new Guid("79d4ef1a-8a4a-4cb2-b63a-2307698de15b"),
                            Name = "NotificationsView"
                        },
                        new
                        {
                            Id = new Guid("274e546f-78b0-4dc2-a7bc-548f5e92f4cc"),
                            Name = "NotificationsManage"
                        },
                        new
                        {
                            Id = new Guid("4a6970f1-ff3e-43fd-9172-c4f3f6c2c4c7"),
                            Name = "AnalyticsView"
                        },
                        new
                        {
                            Id = new Guid("f3a9df19-ea7c-4a90-a3ee-238c7f745f5f"),
                            Name = "MediaManage"
                        },
                        new
                        {
                            Id = new Guid("aa0d8c57-e388-4db4-9746-b6cc4b47fd0d"),
                            Name = "LogsView"
                        },
                        new
                        {
                            Id = new Guid("1740be12-b8a1-40db-b184-d43fd3f6b0fa"),
                            Name = "FinanceView"
                        },
                        new
                        {
                            Id = new Guid("d474449e-3045-4418-89c7-5a7599e58033"),
                            Name = "FinanceManage"
                        });
                });

            modelBuilder.Entity("BadmintonApp.Domain.Core.Player", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<int>("Level")
                        .HasColumnType("INTEGER");

                    b.Property<Guid>("UserId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("Players");
                });

            modelBuilder.Entity("BadmintonApp.Domain.Core.Role", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Roles");

                    b.HasData(
                        new
                        {
                            Id = new Guid("45225223-0e47-4c7a-b045-38de629412e5"),
                            Name = "SuperAdmin"
                        },
                        new
                        {
                            Id = new Guid("98e5cfcd-cada-486a-96bb-30b6a9a60174"),
                            Name = "ClubAdmin"
                        },
                        new
                        {
                            Id = new Guid("bb074c39-08df-45d9-8e74-5b6a07257883"),
                            Name = "ClubManager"
                        },
                        new
                        {
                            Id = new Guid("5b0ac8d3-e270-422f-af95-99e8be79e47a"),
                            Name = "Player"
                        });
                });

            modelBuilder.Entity("BadmintonApp.Domain.Core.RolePermission", b =>
                {
                    b.Property<Guid>("RoleId")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("PermissionId")
                        .HasColumnType("TEXT");

                    b.HasKey("RoleId", "PermissionId");

                    b.HasIndex("PermissionId");

                    b.ToTable("RolePermissions");

                    b.HasData(
                        new
                        {
                            RoleId = new Guid("45225223-0e47-4c7a-b045-38de629412e5"),
                            PermissionId = new Guid("bb144aa6-d452-4c65-8dd8-26e83a343d10")
                        },
                        new
                        {
                            RoleId = new Guid("45225223-0e47-4c7a-b045-38de629412e5"),
                            PermissionId = new Guid("dc24d312-1e12-455e-b58d-6a5e0e1c5a26")
                        },
                        new
                        {
                            RoleId = new Guid("45225223-0e47-4c7a-b045-38de629412e5"),
                            PermissionId = new Guid("c17101a7-c7f5-4cfc-99c4-c9e7bff062e0")
                        },
                        new
                        {
                            RoleId = new Guid("45225223-0e47-4c7a-b045-38de629412e5"),
                            PermissionId = new Guid("e804d9ec-17e5-4cb1-97fd-d033379b2a1e")
                        },
                        new
                        {
                            RoleId = new Guid("45225223-0e47-4c7a-b045-38de629412e5"),
                            PermissionId = new Guid("f42d1226-3c8a-4690-a9cb-702d81e9d134")
                        },
                        new
                        {
                            RoleId = new Guid("45225223-0e47-4c7a-b045-38de629412e5"),
                            PermissionId = new Guid("6e378e33-7c14-41d8-9005-3211ac337ada")
                        },
                        new
                        {
                            RoleId = new Guid("45225223-0e47-4c7a-b045-38de629412e5"),
                            PermissionId = new Guid("fbcc2933-164c-4f37-a9e7-11868c34dc64")
                        },
                        new
                        {
                            RoleId = new Guid("45225223-0e47-4c7a-b045-38de629412e5"),
                            PermissionId = new Guid("bcfd34b3-d0aa-4a84-a68e-d1c58e0a0f36")
                        },
                        new
                        {
                            RoleId = new Guid("45225223-0e47-4c7a-b045-38de629412e5"),
                            PermissionId = new Guid("e30aa5ae-2e19-4a5b-a9be-40cc74bb25e4")
                        },
                        new
                        {
                            RoleId = new Guid("45225223-0e47-4c7a-b045-38de629412e5"),
                            PermissionId = new Guid("4fd7483a-2436-4c2c-bdd3-275e595dcd1e")
                        },
                        new
                        {
                            RoleId = new Guid("45225223-0e47-4c7a-b045-38de629412e5"),
                            PermissionId = new Guid("2264ae2c-73b2-4a8f-8e92-cc38d4cd6b6c")
                        },
                        new
                        {
                            RoleId = new Guid("45225223-0e47-4c7a-b045-38de629412e5"),
                            PermissionId = new Guid("b3a08f9f-263e-42cc-b02a-85b5c6a5979b")
                        },
                        new
                        {
                            RoleId = new Guid("45225223-0e47-4c7a-b045-38de629412e5"),
                            PermissionId = new Guid("66d2b5fd-f0fd-4c29-92d6-e165fce4096f")
                        },
                        new
                        {
                            RoleId = new Guid("45225223-0e47-4c7a-b045-38de629412e5"),
                            PermissionId = new Guid("e47c2949-6cf3-4c2f-b6b0-e252b456cacf")
                        },
                        new
                        {
                            RoleId = new Guid("45225223-0e47-4c7a-b045-38de629412e5"),
                            PermissionId = new Guid("94a13b97-2e03-41df-9c4e-84db8f5a05a1")
                        },
                        new
                        {
                            RoleId = new Guid("45225223-0e47-4c7a-b045-38de629412e5"),
                            PermissionId = new Guid("7c918f93-79b3-4f0f-91de-798a888d8ec9")
                        },
                        new
                        {
                            RoleId = new Guid("45225223-0e47-4c7a-b045-38de629412e5"),
                            PermissionId = new Guid("f88b5e0f-78ec-40b0-ade6-dc6c0414d6b4")
                        },
                        new
                        {
                            RoleId = new Guid("45225223-0e47-4c7a-b045-38de629412e5"),
                            PermissionId = new Guid("6c2dba59-81c2-4d06-a476-66c7cf930a50")
                        },
                        new
                        {
                            RoleId = new Guid("45225223-0e47-4c7a-b045-38de629412e5"),
                            PermissionId = new Guid("9f29376d-dbc5-4a1a-85c3-cd6d0cbac9a6")
                        },
                        new
                        {
                            RoleId = new Guid("45225223-0e47-4c7a-b045-38de629412e5"),
                            PermissionId = new Guid("95a05b7b-e88d-48c1-9e65-0cfc2c4a09f6")
                        },
                        new
                        {
                            RoleId = new Guid("45225223-0e47-4c7a-b045-38de629412e5"),
                            PermissionId = new Guid("79d4ef1a-8a4a-4cb2-b63a-2307698de15b")
                        },
                        new
                        {
                            RoleId = new Guid("45225223-0e47-4c7a-b045-38de629412e5"),
                            PermissionId = new Guid("274e546f-78b0-4dc2-a7bc-548f5e92f4cc")
                        },
                        new
                        {
                            RoleId = new Guid("45225223-0e47-4c7a-b045-38de629412e5"),
                            PermissionId = new Guid("4a6970f1-ff3e-43fd-9172-c4f3f6c2c4c7")
                        },
                        new
                        {
                            RoleId = new Guid("45225223-0e47-4c7a-b045-38de629412e5"),
                            PermissionId = new Guid("f3a9df19-ea7c-4a90-a3ee-238c7f745f5f")
                        },
                        new
                        {
                            RoleId = new Guid("45225223-0e47-4c7a-b045-38de629412e5"),
                            PermissionId = new Guid("aa0d8c57-e388-4db4-9746-b6cc4b47fd0d")
                        },
                        new
                        {
                            RoleId = new Guid("45225223-0e47-4c7a-b045-38de629412e5"),
                            PermissionId = new Guid("1740be12-b8a1-40db-b184-d43fd3f6b0fa")
                        },
                        new
                        {
                            RoleId = new Guid("45225223-0e47-4c7a-b045-38de629412e5"),
                            PermissionId = new Guid("d474449e-3045-4418-89c7-5a7599e58033")
                        },
                        new
                        {
                            RoleId = new Guid("98e5cfcd-cada-486a-96bb-30b6a9a60174"),
                            PermissionId = new Guid("bb144aa6-d452-4c65-8dd8-26e83a343d10")
                        },
                        new
                        {
                            RoleId = new Guid("98e5cfcd-cada-486a-96bb-30b6a9a60174"),
                            PermissionId = new Guid("dc24d312-1e12-455e-b58d-6a5e0e1c5a26")
                        },
                        new
                        {
                            RoleId = new Guid("98e5cfcd-cada-486a-96bb-30b6a9a60174"),
                            PermissionId = new Guid("c17101a7-c7f5-4cfc-99c4-c9e7bff062e0")
                        },
                        new
                        {
                            RoleId = new Guid("98e5cfcd-cada-486a-96bb-30b6a9a60174"),
                            PermissionId = new Guid("e804d9ec-17e5-4cb1-97fd-d033379b2a1e")
                        },
                        new
                        {
                            RoleId = new Guid("98e5cfcd-cada-486a-96bb-30b6a9a60174"),
                            PermissionId = new Guid("f42d1226-3c8a-4690-a9cb-702d81e9d134")
                        },
                        new
                        {
                            RoleId = new Guid("98e5cfcd-cada-486a-96bb-30b6a9a60174"),
                            PermissionId = new Guid("6e378e33-7c14-41d8-9005-3211ac337ada")
                        },
                        new
                        {
                            RoleId = new Guid("98e5cfcd-cada-486a-96bb-30b6a9a60174"),
                            PermissionId = new Guid("fbcc2933-164c-4f37-a9e7-11868c34dc64")
                        },
                        new
                        {
                            RoleId = new Guid("98e5cfcd-cada-486a-96bb-30b6a9a60174"),
                            PermissionId = new Guid("bcfd34b3-d0aa-4a84-a68e-d1c58e0a0f36")
                        },
                        new
                        {
                            RoleId = new Guid("98e5cfcd-cada-486a-96bb-30b6a9a60174"),
                            PermissionId = new Guid("e30aa5ae-2e19-4a5b-a9be-40cc74bb25e4")
                        },
                        new
                        {
                            RoleId = new Guid("98e5cfcd-cada-486a-96bb-30b6a9a60174"),
                            PermissionId = new Guid("4fd7483a-2436-4c2c-bdd3-275e595dcd1e")
                        },
                        new
                        {
                            RoleId = new Guid("98e5cfcd-cada-486a-96bb-30b6a9a60174"),
                            PermissionId = new Guid("2264ae2c-73b2-4a8f-8e92-cc38d4cd6b6c")
                        },
                        new
                        {
                            RoleId = new Guid("98e5cfcd-cada-486a-96bb-30b6a9a60174"),
                            PermissionId = new Guid("b3a08f9f-263e-42cc-b02a-85b5c6a5979b")
                        },
                        new
                        {
                            RoleId = new Guid("98e5cfcd-cada-486a-96bb-30b6a9a60174"),
                            PermissionId = new Guid("66d2b5fd-f0fd-4c29-92d6-e165fce4096f")
                        },
                        new
                        {
                            RoleId = new Guid("98e5cfcd-cada-486a-96bb-30b6a9a60174"),
                            PermissionId = new Guid("e47c2949-6cf3-4c2f-b6b0-e252b456cacf")
                        },
                        new
                        {
                            RoleId = new Guid("98e5cfcd-cada-486a-96bb-30b6a9a60174"),
                            PermissionId = new Guid("94a13b97-2e03-41df-9c4e-84db8f5a05a1")
                        },
                        new
                        {
                            RoleId = new Guid("98e5cfcd-cada-486a-96bb-30b6a9a60174"),
                            PermissionId = new Guid("7c918f93-79b3-4f0f-91de-798a888d8ec9")
                        },
                        new
                        {
                            RoleId = new Guid("98e5cfcd-cada-486a-96bb-30b6a9a60174"),
                            PermissionId = new Guid("f88b5e0f-78ec-40b0-ade6-dc6c0414d6b4")
                        },
                        new
                        {
                            RoleId = new Guid("98e5cfcd-cada-486a-96bb-30b6a9a60174"),
                            PermissionId = new Guid("6c2dba59-81c2-4d06-a476-66c7cf930a50")
                        },
                        new
                        {
                            RoleId = new Guid("98e5cfcd-cada-486a-96bb-30b6a9a60174"),
                            PermissionId = new Guid("9f29376d-dbc5-4a1a-85c3-cd6d0cbac9a6")
                        },
                        new
                        {
                            RoleId = new Guid("98e5cfcd-cada-486a-96bb-30b6a9a60174"),
                            PermissionId = new Guid("95a05b7b-e88d-48c1-9e65-0cfc2c4a09f6")
                        },
                        new
                        {
                            RoleId = new Guid("98e5cfcd-cada-486a-96bb-30b6a9a60174"),
                            PermissionId = new Guid("79d4ef1a-8a4a-4cb2-b63a-2307698de15b")
                        },
                        new
                        {
                            RoleId = new Guid("98e5cfcd-cada-486a-96bb-30b6a9a60174"),
                            PermissionId = new Guid("274e546f-78b0-4dc2-a7bc-548f5e92f4cc")
                        },
                        new
                        {
                            RoleId = new Guid("98e5cfcd-cada-486a-96bb-30b6a9a60174"),
                            PermissionId = new Guid("4a6970f1-ff3e-43fd-9172-c4f3f6c2c4c7")
                        },
                        new
                        {
                            RoleId = new Guid("98e5cfcd-cada-486a-96bb-30b6a9a60174"),
                            PermissionId = new Guid("f3a9df19-ea7c-4a90-a3ee-238c7f745f5f")
                        },
                        new
                        {
                            RoleId = new Guid("98e5cfcd-cada-486a-96bb-30b6a9a60174"),
                            PermissionId = new Guid("aa0d8c57-e388-4db4-9746-b6cc4b47fd0d")
                        },
                        new
                        {
                            RoleId = new Guid("98e5cfcd-cada-486a-96bb-30b6a9a60174"),
                            PermissionId = new Guid("1740be12-b8a1-40db-b184-d43fd3f6b0fa")
                        },
                        new
                        {
                            RoleId = new Guid("98e5cfcd-cada-486a-96bb-30b6a9a60174"),
                            PermissionId = new Guid("d474449e-3045-4418-89c7-5a7599e58033")
                        });
                });

            modelBuilder.Entity("BadmintonApp.Domain.Core.Staff", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("ClubId")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Currency")
                        .HasColumnType("TEXT");

                    b.Property<int>("EmploymentType")
                        .HasColumnType("INTEGER");

                    b.Property<DateOnly?>("EndDate")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("HourlyRate")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("MonthlySalary")
                        .HasColumnType("TEXT");

                    b.Property<string>("Notes")
                        .HasColumnType("TEXT");

                    b.Property<string>("PayrollNotes")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("PerTrainingRate")
                        .HasColumnType("TEXT");

                    b.Property<int>("SalaryType")
                        .HasColumnType("INTEGER");

                    b.Property<int>("StaffStatus")
                        .HasColumnType("INTEGER");

                    b.Property<DateOnly>("StartDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("StatusReason")
                        .HasColumnType("TEXT");

                    b.Property<string>("TimeZone")
                        .HasColumnType("TEXT");

                    b.Property<string>("Title")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("UserId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ClubId");

                    b.HasIndex("UserId");

                    b.ToTable("Staffs");
                });

            modelBuilder.Entity("BadmintonApp.Domain.Core.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("ClubId")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("DoB")
                        .HasColumnType("TEXT");

                    b.Property<string>("Email")
                        .HasColumnType("TEXT");

                    b.Property<string>("FirstName")
                        .HasColumnType("TEXT");

                    b.Property<string>("ImageUrl")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsActive")
                        .HasColumnType("INTEGER");

                    b.Property<string>("LastName")
                        .HasColumnType("TEXT");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("TEXT");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("BadmintonApp.Domain.Core.UserClubRole", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("RoleId")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("ClubId")
                        .HasColumnType("TEXT");

                    b.HasKey("UserId", "RoleId", "ClubId");

                    b.HasIndex("ClubId");

                    b.HasIndex("RoleId");

                    b.ToTable("UserClubRoles");
                });

            modelBuilder.Entity("BadmintonApp.Domain.Core.UserRole", b =>
                {
                    b.Property<Guid>("RoleId")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("UserId")
                        .HasColumnType("TEXT");

                    b.HasKey("RoleId", "UserId");

                    b.HasIndex("UserId");

                    b.ToTable("UserRoles");
                });

            modelBuilder.Entity("BadmintonApp.Domain.Logs.Log", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("ExceptionJson")
                        .HasColumnType("TEXT");

                    b.Property<int>("Level")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Message")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Logs");
                });

            modelBuilder.Entity("BadmintonApp.Domain.Trainings.Training", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.PrimitiveCollection<string>("AllowedLevels")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("ClubId")
                        .HasColumnType("TEXT");

                    b.Property<int>("CourtsUsed")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("Date")
                        .HasColumnType("TEXT");

                    b.Property<TimeOnly>("EndTime")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsRecurringWeekly")
                        .HasColumnType("INTEGER");

                    b.Property<Guid?>("LocationId")
                        .HasColumnType("TEXT");

                    b.Property<int>("MaxPlayers")
                        .HasColumnType("INTEGER");

                    b.Property<TimeOnly>("StartTime")
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("TrainerId")
                        .HasColumnType("TEXT");

                    b.Property<int>("Type")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("Trainings");
                });

            modelBuilder.Entity("BadmintonApp.Domain.Trainings.TrainingParticipant", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("RegisteredAt")
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("TrainingId")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("UserId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("TrainingId");

                    b.ToTable("TrainingParticipants");
                });

            modelBuilder.Entity("BadmintonApp.Domain.Trainings.TrainingQueueEntry", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("QueuedAt")
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("TrainingId")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("UserId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("TrainingId");

                    b.ToTable("TrainingQueueEntries");
                });

            modelBuilder.Entity("BadmintonApp.Domain.WorkingHours.WorkingHour", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("ClubId")
                        .HasColumnType("TEXT");

                    b.Property<int>("DayOfWeek")
                        .HasColumnType("INTEGER");

                    b.Property<TimeOnly>("EndTime")
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("StaffId")
                        .HasColumnType("TEXT");

                    b.Property<TimeOnly>("StartTime")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ClubId");

                    b.HasIndex("StaffId");

                    b.ToTable("WorkingHours");
                });

            modelBuilder.Entity("BadmintonApp.Domain.Core.Player", b =>
                {
                    b.HasOne("BadmintonApp.Domain.Core.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("BadmintonApp.Domain.Core.RolePermission", b =>
                {
                    b.HasOne("BadmintonApp.Domain.Core.Permission", "Permission")
                        .WithMany("RolePermissions")
                        .HasForeignKey("PermissionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BadmintonApp.Domain.Core.Role", "Role")
                        .WithMany("RolePermissions")
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Permission");

                    b.Navigation("Role");
                });

            modelBuilder.Entity("BadmintonApp.Domain.Core.Staff", b =>
                {
                    b.HasOne("BadmintonApp.Domain.Clubs.Club", "Club")
                        .WithMany()
                        .HasForeignKey("ClubId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BadmintonApp.Domain.Core.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Club");

                    b.Navigation("User");
                });

            modelBuilder.Entity("BadmintonApp.Domain.Core.UserClubRole", b =>
                {
                    b.HasOne("BadmintonApp.Domain.Clubs.Club", "Club")
                        .WithMany("UserRoles")
                        .HasForeignKey("ClubId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BadmintonApp.Domain.Core.Role", "Role")
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BadmintonApp.Domain.Core.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Club");

                    b.Navigation("Role");

                    b.Navigation("User");
                });

            modelBuilder.Entity("BadmintonApp.Domain.Core.UserRole", b =>
                {
                    b.HasOne("BadmintonApp.Domain.Core.Role", "Role")
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BadmintonApp.Domain.Core.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Role");

                    b.Navigation("User");
                });

            modelBuilder.Entity("BadmintonApp.Domain.Trainings.TrainingParticipant", b =>
                {
                    b.HasOne("BadmintonApp.Domain.Trainings.Training", null)
                        .WithMany("Participants")
                        .HasForeignKey("TrainingId");
                });

            modelBuilder.Entity("BadmintonApp.Domain.Trainings.TrainingQueueEntry", b =>
                {
                    b.HasOne("BadmintonApp.Domain.Trainings.Training", null)
                        .WithMany("Queue")
                        .HasForeignKey("TrainingId");
                });

            modelBuilder.Entity("BadmintonApp.Domain.WorkingHours.WorkingHour", b =>
                {
                    b.HasOne("BadmintonApp.Domain.Clubs.Club", "Club")
                        .WithMany("WorkingHours")
                        .HasForeignKey("ClubId");

                    b.HasOne("BadmintonApp.Domain.Core.Staff", "Staff")
                        .WithMany("WorkingHours")
                        .HasForeignKey("StaffId");

                    b.Navigation("Club");

                    b.Navigation("Staff");
                });

            modelBuilder.Entity("BadmintonApp.Domain.Clubs.Club", b =>
                {
                    b.Navigation("UserRoles");

                    b.Navigation("WorkingHours");
                });

            modelBuilder.Entity("BadmintonApp.Domain.Core.Permission", b =>
                {
                    b.Navigation("RolePermissions");
                });

            modelBuilder.Entity("BadmintonApp.Domain.Core.Role", b =>
                {
                    b.Navigation("RolePermissions");
                });

            modelBuilder.Entity("BadmintonApp.Domain.Core.Staff", b =>
                {
                    b.Navigation("WorkingHours");
                });

            modelBuilder.Entity("BadmintonApp.Domain.Trainings.Training", b =>
                {
                    b.Navigation("Participants");

                    b.Navigation("Queue");
                });
#pragma warning restore 612, 618
        }
    }
}
