import type { Metadata } from "next";
import { Manrope, Unbounded, Inter } from "next/font/google";
// import Header from "./components/shared/Header/Header";
import Footer from "./components/shared/Footer/Footer";
import "./styles/globals.scss";

const manrope = Manrope({
  subsets: ["latin", "cyrillic"],
  weight: ["400", "500", "600", "700"],
  variable: "--font-sans",
  display: "swap",
});

// заголовки / display
const unbounded = Unbounded({
  subsets: ["latin", "cyrillic"],
  weight: ["400", "600", "700", "800"],
  variable: "--font-display",
  display: "swap",
});
const inter = Inter({
  subsets: ["latin", "cyrillic"],
  weight: ["400", "500", "600", "700"],
  variable: "--font-inter",
  display: "swap",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
     <body className={`${manrope.variable} ${unbounded.variable} ${inter.variable} antialiased`}>
        {/* <Header /> */}
        {children}
        <Footer />
      </body>
    </html>
  );
}
